spring.application.name=springtest

spring.datasource.url=jdbc:mysql://125.212.223.197:3306/apptest
spring.datasource.username=userapptest
spring.datasource.password=Vtdc#1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===== Kafka config (tu nhap thong tin cua ban) =====
spring.kafka.bootstrap-servers=171.237.177.59:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Neu Kafka co SASL/SSL thi mo comment va nhap:
#spring.kafka.properties.security.protocol=SASL_PLAINTEXT
#spring.kafka.properties.sasl.mechanism=PLAIN
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="..." password="...";

# Topic mac dinh cho API push
app.kafka.topic=test-topic

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasiBinder=TRACE
